# Generated by Django 2.0.1 on 2018-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20180223_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
